"""設定値ロジックの facade。"""

from .settings_payload import collect_settings_payload, selected_capture_settings_payload
from .settings_selected_values import (
    selected_analysis_max_dim,
    selected_analysis_resolution_mode,
    selected_binary_preset,
    selected_color_band_harmony_guide_enabled,
    selected_color_band_harmony_guide_type,
    selected_color_band_sat_threshold,
    selected_color_band_use_wheel_harmony,
    selected_color_band_use_wheel_sat_threshold,
    selected_composition_guide,
    selected_diff_threshold,
    selected_edge_sensitivity,
    selected_effective_color_band_sat_threshold,
    selected_effective_color_band_sat_threshold_safe,
    selected_focus_peak_sensitivity,
    selected_focus_peak_thickness,
    selected_focus_peak_color,
    selected_interval,
    selected_mirror_mode,
    selected_mode,
    selected_rgb_hist_mode,
    selected_sample_points,
    selected_saliency_overlay_alpha,
    selected_scatter_hue_center,
    selected_scatter_hue_filter_enabled,
    selected_scatter_render_mode,
    selected_scatter_shape,
    selected_squint_blur_sigma,
    selected_squint_mode,
    selected_squint_scale_percent,
    selected_stable_frames,
    selected_ternary_preset,
    selected_ui_theme,
    selected_vectorscope_show_skin_line,
    selected_vectorscope_warn_threshold,
    selected_wheel_harmony_guide_enabled,
    selected_wheel_harmony_guide_rotation,
    selected_wheel_harmony_guide_type,
    selected_wheel_mode,
    selected_wheel_sat_threshold,
)
from .settings_value_common import (
    apply_combo_choice,
    cfg_float,
    cfg_int,
    selected_checked,
    selected_checked_attr,
    selected_combo_attr,
    selected_combo_data,
    selected_int_attr,
    selected_int_in_range,
    set_combobox_data_blocked,
    set_value_blocked,
)

_cfg_float = cfg_float
_cfg_int = cfg_int
_set_value_blocked = set_value_blocked
_set_combobox_data_blocked = set_combobox_data_blocked
_apply_combo_choice = apply_combo_choice
_selected_combo_data = selected_combo_data
_selected_checked = selected_checked
_selected_checked_attr = selected_checked_attr
_selected_int_in_range = selected_int_in_range
_selected_int_attr = selected_int_attr
_selected_combo_attr = selected_combo_attr
_selected_capture_settings_payload = selected_capture_settings_payload
_collect_settings_payload = collect_settings_payload

__all__ = [
    "_apply_combo_choice",
    "_cfg_float",
    "_cfg_int",
    "_collect_settings_payload",
    "_selected_capture_settings_payload",
    "_selected_checked",
    "_selected_checked_attr",
    "_selected_combo_attr",
    "_selected_combo_data",
    "_selected_int_attr",
    "_selected_int_in_range",
    "_set_combobox_data_blocked",
    "_set_value_blocked",
    "apply_combo_choice",
    "cfg_float",
    "cfg_int",
    "collect_settings_payload",
    "selected_capture_settings_payload",
    "selected_analysis_max_dim",
    "selected_analysis_resolution_mode",
    "selected_binary_preset",
    "selected_color_band_harmony_guide_enabled",
    "selected_color_band_harmony_guide_type",
    "selected_color_band_sat_threshold",
    "selected_color_band_use_wheel_harmony",
    "selected_color_band_use_wheel_sat_threshold",
    "selected_composition_guide",
    "selected_diff_threshold",
    "selected_effective_color_band_sat_threshold",
    "selected_effective_color_band_sat_threshold_safe",
    "selected_edge_sensitivity",
    "selected_focus_peak_sensitivity",
    "selected_focus_peak_thickness",
    "selected_focus_peak_color",
    "selected_interval",
    "selected_checked",
    "selected_checked_attr",
    "selected_combo_attr",
    "selected_combo_data",
    "selected_int_attr",
    "selected_int_in_range",
    "selected_mirror_mode",
    "selected_mode",
    "selected_rgb_hist_mode",
    "selected_sample_points",
    "selected_saliency_overlay_alpha",
    "selected_scatter_hue_center",
    "selected_scatter_hue_filter_enabled",
    "selected_scatter_render_mode",
    "selected_scatter_shape",
    "selected_squint_blur_sigma",
    "selected_squint_mode",
    "selected_squint_scale_percent",
    "selected_stable_frames",
    "selected_ternary_preset",
    "selected_ui_theme",
    "selected_vectorscope_show_skin_line",
    "selected_vectorscope_warn_threshold",
    "selected_wheel_harmony_guide_enabled",
    "selected_wheel_harmony_guide_rotation",
    "selected_wheel_harmony_guide_type",
    "selected_wheel_mode",
    "selected_wheel_sat_threshold",
    "set_combobox_data_blocked",
    "set_value_blocked",
]
