from PySide6.QtGui import QColor

# ROI defaults
DEFAULT_ROI_SIZE = (640, 360)

# Analyzer constraints
ANALYZER_MAX_DIM = 400
ANALYZER_MIN_INTERVAL_SEC = 0.05
ANALYZER_MIN_SAMPLE_POINTS = 500
ANALYZER_MIN_GRAPH_EVERY = 1
ANALYZER_MIN_DIFF_THRESHOLD = 0.5
ANALYZER_MIN_STABLE_FRAMES = 1

# Masks for hue histogram (ignore near-gray/dark)
SAT_MASK_THRESHOLD = 15
VAL_MASK_THRESHOLD = 20

# Capture sources
CAPTURE_SOURCE_WINDOW = "window"
CAPTURE_SOURCE_SCREEN = "screen"
CAPTURE_SOURCES = (CAPTURE_SOURCE_WINDOW, CAPTURE_SOURCE_SCREEN)

# Scatter plot shapes
SCATTER_SHAPE_SQUARE = "square"
SCATTER_SHAPE_TRIANGLE = "triangle"
SCATTER_SHAPES = (SCATTER_SHAPE_SQUARE, SCATTER_SHAPE_TRIANGLE)

# Update modes
UPDATE_MODE_INTERVAL = "interval"
UPDATE_MODE_CHANGE = "change"
UPDATE_MODES = (UPDATE_MODE_INTERVAL, UPDATE_MODE_CHANGE)

# Binary presets
BINARY_PRESET_AUTO = "auto"
BINARY_PRESET_MORE_WHITE = "more_white"
BINARY_PRESET_MORE_BLACK = "more_black"
BINARY_PRESETS = (BINARY_PRESET_AUTO, BINARY_PRESET_MORE_WHITE, BINARY_PRESET_MORE_BLACK)

# Ternary presets
TERNARY_PRESET_STANDARD = "standard"
TERNARY_PRESET_SOFT = "soft"
TERNARY_PRESET_STRONG = "strong"
TERNARY_PRESETS = (TERNARY_PRESET_STANDARD, TERNARY_PRESET_SOFT, TERNARY_PRESET_STRONG)

# Focus peaking colors
FOCUS_PEAK_COLOR_CYAN = "cyan"
FOCUS_PEAK_COLOR_GREEN = "green"
FOCUS_PEAK_COLOR_YELLOW = "yellow"
FOCUS_PEAK_COLOR_RED = "red"
FOCUS_PEAK_COLORS = (
    FOCUS_PEAK_COLOR_CYAN,
    FOCUS_PEAK_COLOR_GREEN,
    FOCUS_PEAK_COLOR_YELLOW,
    FOCUS_PEAK_COLOR_RED,
)
FOCUS_PEAK_COLOR_BGR = {
    FOCUS_PEAK_COLOR_CYAN: (255, 235, 0),
    FOCUS_PEAK_COLOR_GREEN: (0, 245, 120),
    FOCUS_PEAK_COLOR_YELLOW: (0, 225, 255),
    FOCUS_PEAK_COLOR_RED: (60, 60, 255),
}

# Squint modes
SQUINT_MODE_BLUR = "blur"
SQUINT_MODE_SCALE = "scale"
SQUINT_MODE_SCALE_BLUR = "scale_blur"
SQUINT_MODES = (
    SQUINT_MODE_BLUR,
    SQUINT_MODE_SCALE,
    SQUINT_MODE_SCALE_BLUR,
)

# Vectorscope
VECTORSCOPE_SIZE = 256
VECTORSCOPE_SKIN_LINE_ANGLE_DEG = 123.0
VECTORSCOPE_SKIN_LINE_INNER_RATIO = 0.04
VECTORSCOPE_SKIN_LINE_OUTER_RATIO = 0.92

# Composition guides
COMPOSITION_GUIDE_NONE = "none"
COMPOSITION_GUIDE_THIRDS = "thirds"
COMPOSITION_GUIDE_CENTER = "center"
COMPOSITION_GUIDE_DIAGONAL = "diagonal"
COMPOSITION_GUIDES = (
    COMPOSITION_GUIDE_NONE,
    COMPOSITION_GUIDE_THIRDS,
    COMPOSITION_GUIDE_CENTER,
    COMPOSITION_GUIDE_DIAGONAL,
)

# General defaults
DEFAULT_INTERVAL_SEC = 0.5
DEFAULT_SAMPLE_POINTS = 10000
DEFAULT_GRAPH_EVERY = 1
DEFAULT_CAPTURE_SOURCE = CAPTURE_SOURCE_WINDOW
DEFAULT_SCATTER_SHAPE = SCATTER_SHAPE_SQUARE
DEFAULT_EDGE_SENSITIVITY = 50
DEFAULT_BINARY_PRESET = BINARY_PRESET_AUTO
DEFAULT_TERNARY_PRESET = TERNARY_PRESET_STANDARD
DEFAULT_SALIENCY_OVERLAY_ALPHA = 65
DEFAULT_COMPOSITION_GUIDE = COMPOSITION_GUIDE_NONE
DEFAULT_FOCUS_PEAK_SENSITIVITY = 20
DEFAULT_FOCUS_PEAK_COLOR = FOCUS_PEAK_COLOR_RED
DEFAULT_FOCUS_PEAK_THICKNESS = 1.0
DEFAULT_SQUINT_MODE = SQUINT_MODE_SCALE_BLUR
DEFAULT_SQUINT_SCALE_PERCENT = 18
DEFAULT_SQUINT_BLUR_SIGMA = 1.8
DEFAULT_VECTORSCOPE_SHOW_SKIN_LINE = True
DEFAULT_PREVIEW_WINDOW = False

# Color bins (label, ranges, rgb) — より細かく12分割程度
HUE_BINS = [
    ("R", [(0, 8), (172, 180)], (255, 40, 40)),
    ("RO", [(8, 22)], (255, 90, 40)),
    ("O", [(22, 30)], (255, 140, 50)),
    ("OY", [(30, 40)], (255, 190, 60)),
    ("Y", [(40, 50)], (245, 215, 70)),
    ("YG", [(50, 70)], (180, 220, 60)),
    ("G", [(70, 95)], (60, 185, 80)),
    ("GB", [(95, 115)], (40, 180, 150)),
    ("C", [(115, 130)], (60, 200, 210)),
    ("B", [(130, 150)], (70, 130, 255)),
    ("PB", [(150, 165)], (130, 90, 255)),
    ("P", [(165, 172)], (200, 80, 220)),
]

# UI colors for histograms
H_COLOR = QColor(220, 90, 90)
S_COLOR = QColor(90, 170, 90)
V_COLOR = QColor(80, 140, 240)

# Change-trigger defaults
DEFAULT_MODE = UPDATE_MODE_INTERVAL
DEFAULT_DIFF_THRESHOLD = 4.0
DEFAULT_STABLE_FRAMES = 3

# UI behavior defaults
WINDOW_LIST_MAX_ITEMS = 500
VIEW_MIN_SIZE = 48

# Shared UI ranges
EDGE_SENSITIVITY_MIN = 1
EDGE_SENSITIVITY_MAX = 100
SALIENCY_ALPHA_MIN = 0
SALIENCY_ALPHA_MAX = 100
FOCUS_PEAK_SENSITIVITY_MIN = 1
FOCUS_PEAK_SENSITIVITY_MAX = 100
FOCUS_PEAK_THICKNESS_MIN = 0.1
FOCUS_PEAK_THICKNESS_MAX = 6.0
FOCUS_PEAK_THICKNESS_STEP = 0.1
SQUINT_SCALE_PERCENT_MIN = 2
SQUINT_SCALE_PERCENT_MAX = 100
SQUINT_BLUR_SIGMA_MIN = 0.0
SQUINT_BLUR_SIGMA_MAX = 30.0
SQUINT_BLUR_SIGMA_STEP = 0.1

# Top-color display
TOP_COLORS_TITLE = "色割合TOP5"
TOP_COLORS_COUNT = 5
TOP_COLOR_BAR_HEIGHT = 24

# Config keys
CFG_INTERVAL = "interval"
CFG_SAMPLE_POINTS = "sample_points"
CFG_SCATTER_SHAPE = "scatter_shape"
CFG_GRAPH_EVERY = "graph_every"
CFG_CAPTURE_SOURCE = "capture_source"
CFG_EDGE_SENSITIVITY = "edge_sensitivity"
CFG_BINARY_PRESET = "binary_preset"
CFG_TERNARY_PRESET = "ternary_preset"
CFG_SALIENCY_OVERLAY_ALPHA = "saliency_overlay_alpha"
CFG_COMPOSITION_GUIDE = "composition_guide"
CFG_FOCUS_PEAK_SENSITIVITY = "focus_peak_sensitivity"
CFG_FOCUS_PEAK_COLOR = "focus_peak_color"
CFG_FOCUS_PEAK_THICKNESS = "focus_peak_thickness"
CFG_SQUINT_MODE = "squint_mode"
CFG_SQUINT_SCALE_PERCENT = "squint_scale_percent"
CFG_SQUINT_BLUR_SIGMA = "squint_blur_sigma"
CFG_VECTORSCOPE_SHOW_SKIN_LINE = "vectorscope_show_skin_line"
CFG_PREVIEW_WINDOW = "preview_window"
CFG_MODE = "mode"
CFG_DIFF_THRESHOLD = "diff_threshold"
CFG_STABLE_FRAMES = "stable_frames"
CFG_LAYOUT_CURRENT = "layout_current"
CFG_LAYOUT_PRESETS = "layout_presets"
